plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.logtail:logback-logtail:0.3.9'
    implementation 'ch.qos.logback:logback-classic:1.5.38'
    implementation 'ch.qos.logback:logback-core:1.5.38'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.22.3'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.22.3'
    implementation 'org.slf4j:slf4j-api:2.0.17'
}

application {
    mainClass = 'com.logtail.example.App'
}
